---
kind: pipeline
type: docker
name: adforge

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: install
    image: node:18
    commands:
      - npm ci

  - name: build
    image: node:18
    commands:
      - npm run build

  - name: deploy
    image: alpine
    volumes:
      - name: shared
        path: /var/shared/adforge
    commands:
      - rm -rf /var/shared/website/*
      - cp -r build/* /var/shared/website/

volumes:
  - name: shared
    host:
      path: /var/shared/website
---
kind: signature
hmac: 0599bacec85e4312237fb9fd4d5a0764f1246d89e1812f1b732b1c8a49ee88d3

...
